perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0.1
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0.2
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0.3
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0.4
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0.5
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0.6
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0.7
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0.8
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 0.9
perl tango.pl --taxonomy  GREENGENE_10022015.prep --matches /scratch/RhumatoPhase2/POIPOL/POIPOL_M3_demulti.match  --output test --q-value 1